export const defaultProducts = [
  {
    id: 'bissap',
    name: 'Bissap Boost',
    tagline: 'Énergie tropicale',
    description: "Le rouge profond de l'hibiscus, l'éclat de l'ananas et la fraîcheur de la menthe.",
    ingredients: ['Bissap', 'Ananas', 'Menthe'],
    color: 'from-rose-700 via-red-800 to-rose-900',
    imagePos: '61% 72%',
    emoji: '🌺',
    price: 5,
    imageZoom: 380,
    imageBrightness: 100,
    imageContrast: 100,
    image: '',
  },
  {
    id: 'detox',
    name: 'Fresh Detox',
    tagline: 'Purifiant & vif',
    description: 'Pomme verte, gingembre piquant, citron éclatant et menthe fraîche. La detox premium.',
    ingredients: ['Pomme', 'Gingembre', 'Citron', 'Menthe'],
    color: 'from-lime-500 via-yellow-500 to-amber-600',
    imagePos: '16% 72%',
    emoji: '🍏',
    price: 5,
    imageZoom: 380,
    imageBrightness: 100,
    imageContrast: 100,
    image: '',
  },
  {
    id: 'vita',
    name: 'Vita Orange',
    tagline: 'Vitamine pure',
    description: 'Carotte sucrée, orange juteuse et touche de menthe. Le boost solaire matinal.',
    ingredients: ['Carotte', 'Orange', 'Menthe'],
    color: 'from-orange-400 via-amber-500 to-orange-600',
    imagePos: '39% 72%',
    emoji: '🍊',
    price: 5,
    imageZoom: 380,
    imageBrightness: 100,
    imageContrast: 100,
    image: '',
  },
  {
    id: 'water',
    name: 'Water Fresh',
    tagline: 'Hydratation extrême',
    description: "Pastèque juteuse, citron pétillant et menthe glaciale. La fraîcheur ultime de l'été.",
    ingredients: ['Pastèque', 'Citron', 'Menthe'],
    color: 'from-pink-500 via-rose-500 to-red-600',
    imagePos: '84% 72%',
    emoji: '🍉',
    price: 5,
    imageZoom: 380,
    imageBrightness: 100,
    imageContrast: 100,
    image: '',
  },
]
